# Gitlab Continuous Integration Config
---
# Build JAVA applications using Apache Maven (http://maven.apache.org)

image: gljava:latest

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.repo.local=/cache/maven"

# Cache downloaded dependencies and plugins between builds.
# Does not work?!?
cache:
  paths:
    - /root/.m2

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean compile'

test:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'
